version: 2
updates:
- package-ecosystem: nuget
  directory: /dependabotSamples/dotnet/
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/New_York
  assignees:
  - samsmithnz
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: /src/RepoAutomation.Service/
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/New_York
  assignees:
  - samsmithnz
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: /src/RepoAutomation.Tests/bin/Debug/net6.0/RepoAutomation/src/RepoAutomation.Tests/
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/New_York
  assignees:
  - samsmithnz
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: /src/RepoAutomation.Tests/bin/Debug/net6.0/RepoAutomation/src/RepoAutomation/
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/New_York
  assignees:
  - samsmithnz
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: /src/RepoAutomation.Tests/bin/Debug/net6.0/RepoTestProject/src/RepoTestProject.Tests/
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/New_York
  assignees:
  - samsmithnz
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: /src/RepoAutomation.Tests/bin/Debug/net6.0/RepoTestProject/src/RepoTestProject.Web/
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/New_York
  assignees:
  - samsmithnz
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: /src/RepoAutomation.Tests/
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/New_York
  assignees:
  - samsmithnz
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: /src/RepoAutomation.Web/
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/New_York
  assignees:
  - samsmithnz
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: /src/RepoAutomation/bin/Debug/net6.0/src/RepoAutomationTest.Tests/
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/New_York
  assignees:
  - samsmithnz
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: /src/RepoAutomation/bin/Debug/net6.0/src/RepoAutomationTest.Web/
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/New_York
  assignees:
  - samsmithnz
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: /src/RepoAutomation/
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/New_York
  assignees:
  - samsmithnz
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/New_York
  assignees:
  - samsmithnz
  open-pull-requests-limit: 10
