name: 'CI/ CD'

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  #Install and calculate the new version with GitVersion  
  versionAndTest:
    runs-on: windows-latest
    outputs: 
      Version: ${{ steps.gitversion.outputs.SemVer }} 
      CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }}  
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 #fetch-depth is needed for GitVersion
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.15
      with:
        versionSpec: 5.x
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.15
      id: gitversion # step id used as reference for output values
    - name: Display GitVersion outputs
      run: |
        echo "Version: ${{ steps.gitversion.outputs.SemVer }}"
        echo "CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }}"
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Variable Substitution appsettings file for tests
      uses: microsoft/variable-substitution@v1
      with:
        files: 'src/RepoAutomation.Tests/appsettings.json'
      env:
        AppSettings.GitHubClientId: "${{ secrets.GitHubClientId }}"
        AppSettings.GitHubClientSecret: "${{ secrets.GitHubClientSecret }}" 
    - name: .NET test
      run: dotnet test src/RepoAutomation.Tests/RepoAutomation.Tests.csproj -c Debug -e:CollectCoverage=true -e:CoverletOutput=TestResults/ -e:CoverletOutputFormat=lcov #-l:"trx;LogFileName=${{ github.workspace }}/TestOutput.xml" 
    #- uses: samsmithnz/DotNetTestResults@0.1.3
    #  if: false
    #  with:
    #    fileName: ${{ github.workspace }}/TestOutput.xml
    - name: Publish coverage report to coveralls.io
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: src/RepoAutomation.Tests/TestResults/coverage.info

  build:
    runs-on: ${{matrix.os}}
    needs: versionAndTest
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        #include:
        #- ChannelName: Windows_x64
        #  RID: win-x64
        #- ChannelName: MacOS_x64
        #  RID: osx-x64
        #- ChannelName: Linux_x64
        #  RID: linux-x64
    env:
      BuildConfiguration: Release
    outputs: # https://stackoverflow.com/questions/59175332/using-output-from-a-previous-job-in-a-new-one-in-a-github-action
      Version: ${{ steps.gitversion.outputs.SemVer }}
      CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }}  
    steps:
    - uses: actions/checkout@v3    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    #- name: Create directory for channel
    #  run: mkdir ${{ github.workspace }}\${{ matrix.ChannelName }}
    #  shell: powershell
    #- name: dotnet publish ${{ matrix.RID }}
    #  run: dotnet publish '.\src\RepoAutomation\RepoAutomation.csproj' -r ${{ matrix.RID }} --self-contained -c ${{ env.BuildConfiguration }} -o ${{ github.workspace }}\${{ needs.versionAndTest.outputs.Version }}_${{ matrix.ChannelName }} /p:Version=${{ needs.versionAndTest.outputs.Version }}
    #- name: zip files
    #  run: |
    #    Compress-Archive -Path '${{ github.workspace }}\${{ needs.versionAndTest.outputs.Version }}_${{ matrix.ChannelName }}\' `
    #    -DestinationPath ${{ github.workspace }}\${{ matrix.ChannelName }}\RepoAutomation.${{ matrix.ChannelName }}.${{ needs.versionAndTest.outputs.Version }}.zip
    #  shell: powershell
    #- name: Publish Artifacts
    #  uses: actions/upload-artifact@v3
    #  with:
    #    name: ${{ matrix.ChannelName }}
    #    path: ${{ github.workspace }}\${{ matrix.ChannelName }}    
    #Pack the code into a NuGet package
    - name: .NET pack
      if: runner.OS == 'Linux' #Only pack the Linux nuget package
      run: dotnet pack src/RepoAutomation.Core/RepoAutomation.Core.csproj -c Release --nologo --include-symbols -p:Version='${{ needs.versionAndTest.outputs.Version }}'
    - name: Upload nuget package back to GitHub
      uses: actions/upload-artifact@v3
      if: runner.OS == 'Linux' #Only pack the Linux nuget package
      with:
        name: nugetPackage
        path: src/RepoAutomation.Core/bin/Release  

        
  sonarCloud:
    name: Run SonarCloud analysis
    runs-on: windows-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 1.11
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Install .NET 7 SDK
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: 7.0.x
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v3
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"samsmithnz_RepoAutomation" /o:"samsmithnz-github" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
          dotnet build src/RepoAutomation/RepoAutomation.csproj
          dotnet build src/RepoAutomation.Core/RepoAutomation.Core.csproj
          dotnet build src/RepoAutomation.Tests/RepoAutomation.Tests.csproj
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

        
  Release:
    runs-on: ubuntu-latest
    needs: 
    - build
    - versionAndTest
    - sonarCloud
    if: github.ref == 'refs/heads/main'      
    steps:
    - name: Display GitVersion outputs
      run: |
        echo "Version: ${{ needs.versionAndTest.outputs.Version }}" 
        echo "CommitsSinceVersionSource: ${{ needs.versionAndTest.outputs.CommitsSinceVersionSource }}" 
    - name: Download package artifacts
      uses: actions/download-artifact@v3
    - name: Create Release
      uses: ncipollo/release-action@v1
      if: needs.versionAndTest.outputs.CommitsSinceVersionSource > 0 #Only create a release if there has been a commit/version change
      with:
        #artifacts: Linux_x64/RepoAutomation.Linux_x64.${{ needs.versionAndTest.outputs.Version }}.zip,MacOS_x64/RepoAutomation.MacOS_x64.${{ needs.versionAndTest.outputs.Version }}.zip,Windows_x64/RepoAutomation.Windows_x64.${{ needs.versionAndTest.outputs.Version }}.zip
        tag: ${{ needs.versionAndTest.outputs.Version }}
        name: Release ${{ needs.versionAndTest.outputs.Version }}
        token: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
    - name: Publish nuget package to nuget.org
      if: needs.versionAndTest.outputs.CommitsSinceVersionSource > 0 #Only publish a NuGet package if there has been a commit/version change
      run: dotnet nuget push nugetPackage\*.nupkg --api-key "${{ secrets.GHPackagesToken }}" --source "https://api.nuget.org/v3/index.json"
      shell: pwsh